// vue-app/src/App.vue
<script setup>
import { playerConfig } from "../../react-app/src/data";
import { ref, onMounted } from "vue";

const player = ref(null);
window.questionListUrl = "https://staging.sunbirded.org/api/question/v1/list";

onMounted(() => {
  console.log("player", player.value);
  player.value.addEventListener("playerEvent", (event) => {
    console.log("onPlayerEvent", event.detail);
  });

  player.value.addEventListener("telemetryEvent", (event) => {
    console.log("onTelemetryEvent", event.detail);
  });
});

</script>

<template>
  <div class="container">
    <sunbird-quml-player :playerConfig="playerConfig" ref="player"></sunbird-quml-player>
  </div>
</template>

<style scoped>
.container {
  width: 100%;
  height: 100vh;
  margin: 0 auto;
  display: grid;
  padding-top: 1rem;
}

html,
body {
  background-color: #fff;
}
</style>

// react-app/src/App.js
import { useRef, useEffect } from "react";
import "./App.css";
import "./sunbird/styles.css";
import "./sunbird/sunbird-quml-player";
import { playerConfig } from "./data";

function App() {
  const sunbirdQumlPlayerRef = useRef(null);
  // window.jQuery = $;
  window.questionListUrl = "https://staging.sunbirded.org/api/question/v1/list";
  useEffect(() => {
    const playerElement = sunbirdQumlPlayerRef.current;
    const handlePlayerEvent = (event) => {
      console.log("Player Event", event.detail);
    };
    const handleTelemetryEvent = (event) => {
      console.log("Telemetry Event", event.detail);
    };

    playerElement.addEventListener("playerEvent", handlePlayerEvent);
    playerElement.addEventListener("telemetryEvent", handleTelemetryEvent);

    return () => {
      playerElement.removeEventListener("playerEvent", handlePlayerEvent);
      playerElement.removeEventListener("telemetryEvent", handleTelemetryEvent);
    };
  }, []);
  return (
    <div className="App">
      <sunbird-quml-player
        player-config={JSON.stringify(playerConfig)}
        ref={sunbirdQumlPlayerRef}
      ></sunbird-quml-player>
    </div>
  );
}

export default App;
